<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Nas" ignored="0" name="Test" tests="1" failures="1" timestamp="2022-04-16T13:54:16 EDT" time="16.347" errors="0">
  <testcase name="addition" time="3.788" classname="com.enthrall.mobile.oct21.practice.CalulatorTests">
    <failure type="java.lang.AssertionError" message="expected [10] but found [13]">
      <![CDATA[java.lang.AssertionError: expected [10] but found [13]
at com.enthrall.mobile.oct21.practice.CalulatorTests.addition(CalulatorTests.java:18)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- addition -->
</testsuite> <!-- Test -->
